name: Nightly ETL

on:
  schedule:
    - cron: '39 6 * * *'  # Runs every day at 00:39 Calgary time (MDT = UTC-6)
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests openpyxl pandas

      - name: Ensure logs dir is created and tracked
        run: |
          mkdir -p data/logs
          touch data/logs/.gitkeep
          
      - name: Show log files
        run: |
          echo "Log directory contents:"
          ls -lh data/logs/

      - name: Run ETL scripts
        run: |
          python etl/fetch_author_metrics.py --input data/full_time_faculty.csv --output data/roster_with_metrics.csv
          python etl/UCVM_works.py --input data/roster_with_metrics.csv --output data/openalex_all_authors_last5y_key_fields_dedup.csv 

      - name: Stage new log files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data/logs/*.log || true
          git commit -m "Add ETL run logs" || echo "Nothing to commit"
          git push || echo "Nothing to push"

      - name: Commit and push updates
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data/*.csv
          git commit -m "Nightly data update" || echo "No changes to commit"
          git push
